cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$',
            views.cart_add,
            name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$',
            views.cart_remove,
            name='cart_remove'),
]

myrank/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^', include('rank.urls', namespace='rank')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^create/$',
            views.order_create,
            name='order_create'),
        url(r'^error_paid/$',
            views.error_paid,
            name='error_paid')
]

rank/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    #url(r'^search/', views.search, name='search'),
    #url(r'^$', views.login, name='login'),
    url(r'^search/$', views.search, name='search'),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^$', views.show_product, name='show_product'),
    url(r'^commentcreate/(?P<product_slug>[-\w]+)/(?P<order_id>[-\w]+)/$',views.comment_create,name='comment_create'),
    url(r'^show/', 
        views.show_product, 
        name='show_product'),
        #url(r'^remove/(?P<product_id>\d+)/$',
    url(r'^showme/', 
        views.show_me, 
        name='show_me'),
    url(r'^(?P<restaurant_slug>[-\w]+)/$', 
        views.show_product, 
        name='product_list_by_restaurant'),
   
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', 
        views.product_detail, 
        name='product_detail')]

    
   # r'^remove/(?P<product_id>\d+)/$'
   # url(r'^show_product/(?P<restaurant_name>[-\w]+)/$', 
       # views.show_product, 
       # name='show_product'),
        

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms   

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                choices=PRODUCT_QUANTITY_CHOICES,
                coerce=int,
                label = "数量")
    update = forms.BooleanField(required=False,
                initial=False,
                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from rank.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from rank.models import Myself

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                quantity=cd['quantity'],
                update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    myself=Myself.objects.get(name='ck')
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                    initial={'quantity': item['quantity'],
                                    'update': True})
    return render(request, 'cart/detail.html', {'cart': cart,
                                                'myself':myself})

cart/templates/cart/detail.html
{% extends "rank/base.html" %}
{% load static %}

{% block title %}
    您的购物车
{% endblock %}

{% block content %}
    <h1>您的购物车</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>图片</th>
                <th>产品</th>
                <th>数量</th>
                <th>删除</th>
                <th>单价</th>                
                <th>总价</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>
                <form action="{% url "cart:cart_add" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="更新">
                {% csrf_token %}
                </form>
                </td>

                <td><a href="{% url "cart:cart_remove" product.id %}">删除</a></td>
                <td class="num">￥{{ item.price }}</td>
                <td class="num">￥{{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>总价</td>
            <td colspan="4"></td>
            <td class="num">￥{{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "rank:show_product" %}" class="button light">继续点单</a>
        {% if cart.get_total_price <= myself.balance %}
            <a href="{% url "orders:order_create" %}" class="button">
                结算
            </a>
        {% else %}
            <a href="{% url "orders:error_paid" %}" class="button">
                结算
            </a>
        {% endif %}
    </p>
{% endblock %}