cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$',
            views.cart_add,
            name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$',
            views.cart_remove,
            name='cart_remove'),
]

myrank/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^', include('rank.urls', namespace='rank')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

rank/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    #url(r'^search/', views.search, name='search'),
    #url(r'^$', views.login, name='login'),
    url(r'^search/$', views.search, name='search'),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^$', views.show_product, name='show_product'),
    url(r'^commentcreate/(?P<product_slug>[-\w]+)/(?P<order_id>[-\w]+)/$',views.comment_create,name='comment_create'),
    url(r'^show/', 
        views.show_product, 
        name='show_product'),
        #url(r'^remove/(?P<product_id>\d+)/$',
    url(r'^showme/', 
        views.show_me, 
        name='show_me'),
    url(r'^(?P<restaurant_slug>[-\w]+)/$', 
        views.show_product, 
        name='product_list_by_restaurant'),
   
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', 
        views.product_detail, 
        name='product_detail')]

    
   # r'^remove/(?P<product_id>\d+)/$'
   # url(r'^show_product/(?P<restaurant_name>[-\w]+)/$', 
       # views.show_product, 
       # name='show_product'),
        

rank/models.py
from django.db import models
from django.core.urlresolvers import reverse


# Create your models here.
class Restaurant(models.Model):
	 name = models.CharField(max_length=200,
							      db_index=True)
	 slug = models.SlugField(max_length=200,
	                        db_index=True,
							       unique=True)
	 class Meta:
		  ordering = ('name',)
		  verbose_name = 'restaurant'
		  verbose_name_plural = 'restaurants'
 
	 def __str__(self):
		  return self.name
	 def get_absolute_url(self):
		  return reverse('rank:product_list_by_restaurant',
                        args=[self.slug])


class Product(models.Model):
    restaurant = models.ForeignKey(Restaurant, 
                                 related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    grade = models.FloatField(default=0.00)
    myrank = models.FloatField(default=0.00)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('rank:product_detail',
            args=[self.id, self.slug])


class Myself(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    psw = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    balance = models.DecimalField(max_digits=10, decimal_places=2)
  
    class Meta:
        ordering = ('name',)
        verbose_name = 'myself'
        verbose_name_plural = 'myselfs'
 
    def __str__(self):
        return self.name

class Comment(models.Model):
    product = models.ForeignKey(Product,related_name='comments')
    myself = models.ForeignKey(Myself,related_name='comments')
    slug = models.SlugField(max_length=200, db_index=True)
    des = models.TextField(blank=True)
    score = models.FloatField(default=0.00)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'
   
    #def __str__(self):
     #   return self.name

rank/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import Comment,Myself

class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['des']

class MyselfCreateForm(forms.ModelForm):
    class Meta:
        model = Myself
        fields = ['name', 'psw']

rank/views.py
# -*- coding: utf-8 -*-
#from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404
from .models import Restaurant, Product, Myself, Comment
from orders.models import Order,OrderItem
from cart.forms import CartAddProductForm
from .forms import CommentCreateForm,MyselfCreateForm
from django.db.models import Q


def product_list(request, restaurant_slug=None):
    restaurant = None
    restaurants = Restaurant.objects.all()
    products = Product.objects.filter(available=True)
    comments = Comment.objects.all()
    
    if restaurant_slug:
        restaurant = get_object_or_404(Restaurant, slug=restaurant_slug)
        products = products.filter(restaurant=restaurant)
    product1 = products.filter(Q(slug__icontains='no1'))[:5]
    product2 = products.filter(Q(slug__icontains='no2'))[:5]
    product3 = products.filter(Q(slug__icontains='no3'))[:5]
    product4 = products.filter(Q(slug__icontains='no4'))[:5]
    product5 = products.filter(Q(slug__icontains='no5'))[:5]
    orderitems = OrderItem.objects.all()
    myproduct = Product.objects.all()
   
    for product in products:
        num=product.grade
        p=Product.objects.get(name=product.name)
        if(orderitems):
            for ordernum in orderitems:
                if ordernum.product.name == product.name:
                    num=num+1
            if num!=0:
                p.grade=num
                p.save()
    order2 = Order.objects.filter(name='ck')
    for pro in myproduct:
        pro.myrank=0
        for order3 in order2:
            myorder = OrderItem.objects.filter(order=order3)
            for items in myorder:
                if items.product.name==pro.name:
                    pro.myrank=pro.myrank+1
        pro.save()
    rank = myproduct.order_by("-myrank")[0:5]
            
    products_rank=Product.objects.order_by("-grade")[0:10]
    return render(request, 
                  'rank/product/list.html', 
                  {'restaurant': restaurant,
                  'restaurants': restaurants,
                  'products': products,
                  'comments': comments,
                  'products_rank':products_rank,
                  'product1':product1,
                  'product2':product2,
                  'product3':product3,
                  'product4':product4,
                  'product5':product5,
                  'myrank':rank,
                  'myorder':myorder,
                  'order':order2})

def product_detail(request, id, slug):
    product = get_object_or_404(Product, 
                                id=id, 
                                slug=slug, 
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 
                  'rank/product/detail.html', 
                  {'product': product,
                   'cart_product_form': cart_product_form})
def show_product(request,restaurant_slug=None):
    product = Product.objects.filter(available=True)
    restaurant = None
    restaurants = Restaurant.objects.order_by("id")
    products = Product.objects.filter(available=True)
    if restaurant_slug:
        restaurant = get_object_or_404(Restaurant, slug=restaurant_slug)
        products = products.filter(restaurant=restaurant)
    return render(request,
                  'rank/product/show_product.html',
                  {'product':product,
                   'restaurant':restaurant,
                  'restaurants': restaurants,
                  'products': products,})
def show_me(request):
    myself = Myself.objects.filter(name='ck')
    order = Order.objects.filter(name='ck',paid=False)
    order2 = Order.objects.filter(name='ck',paid=True)[0:10]
    orderitems = OrderItem.objects.all()
    product = Product.objects.all()

    return render(request,
                  'rank/product/show_me.html',
                  {'myself':myself,
                   'orderitems':orderitems,
                   'product':product,
                   'order':order,
                   'order2':order2})
def comment_create(request,product_slug,order_id):
        product=Product.objects.get(slug=product_slug)
        myself = Myself.objects.get(name='ck')
        form = CommentCreateForm(request.POST)
        order=Order.objects.get(id=order_id)
        if request.method == 'POST':
            form = CommentCreateForm(request.POST)
            if form.is_valid():
                  comment1=Comment(product=product,
                                   myself=myself,
                                   des=form['des'],
                                   score=1)
                  order.paid=True
                  order.save()
                  comment1.save()
                  return render(request,
                              'rank/product/commentcreated.html',
                              {})
        else:
            form = CommentCreateForm()
            return render(request,
                                   'rank/product/comment_create.html',
                                   {'form': form,
                                    'product_slug':product_slug,
                                    'order_id':order_id})
        
        

def search(request):
    request.encoding='utf-8'
    q = request.GET.get('q')
    error_msg = ''
    allproduct=Product.objects.all()
    if not q:
        error_msg = '请输入关键词'
        return render(request, 'rank/product/search.html', {'error_msg': error_msg})
    
    post_list = allproduct.filter(Q(name__icontains=q))
    return render(request, 
                  'rank/product/search.html', 
                  {'error_msg': error_msg,
                   'post_list':post_list})
        
        
 
 # Create your views here.

rank/templates/rank/product/comment_create.html
{% extends "rank/base.html" %}
{% block title %}
评价
{% endblock %}
{% block content %}
    <h1>评价</h1>
<form action="." method="post">
    {{ form.as_p }}
    <p><input type="submit" value="Place comment"></p>
    {% csrf_token %}
</form>
{% endblock %}

rank/templates/rank/product/commentcreated.html
{% extends "rank/base.html" %}

{% block title %}
评价成功
{% endblock %}

{% block content %}
<strong>感谢您的评价，食堂因你们而更好</strong>.</p>
{% endblock %}

rank/templates/rank/product/detail.html
{% extends "rank/base.html" %}
{% load static %}

{% block title %}
    {% if restaurant %}{{ restaurant.title }}{% else %}菜品{% endif %}
{% endblock %}

{% block content %}
    <div class="product-detail">
        <img class="my-img2" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.restaurant.get_absolute_url }}">({{ product.restaurant }})</a></h2>
        <p class="price">￥{{ product.price }}</p>
            {{ product.description|linebreaks }}
    </div>

<form action="{% url "cart:cart_add" product.id %}" method="post">
{{ cart_product_form }}
{% csrf_token %}

<input type="submit" value="加入购物车">
</form>
{% endblock %}

rank/templates/rank/product/list.html
{% extends "rank/base.html" %}
{% load static %}

{% block title %}
    {% if restaurant %}{{ restaurant.name }}{% else %}菜单{% endif %}
{% endblock %}

{% block content %}

    <div id="main" class="product-list">
        <div class="ever" ><strong>每日推荐</strong></div>
            {% for items in myrank %}
            <div class="item">
               <a href="{{ items.get_absolute_url }}">
                    <img class="my-img" src="{% if items.image %}{{ items.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                </a></br>
                <a href="{{ items.get_absolute_url }}">{{ items.name }}</a></br>
            </div>
            {% endfor %}
            
    </div>
    <h4 style="font-size:20px;color:red;"><strong>今日菜单</strong></h4>
    <h4>一号食堂</h4>
    <table class="cart">
        <tbody>
            <tr>
                <th>菜名</th>
                <th>价格</th>
                <th>余量</th>
                <th>人气值</th>
            </tr>
            {% for product in product1 %}
                <tr>
                    {% if product.restaurant.name == '一号食堂' %}
                        <td><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></td>
                        <td>￥{{ product.price }}</td>
                        <td>{{ product.stock }}</td>
                        <td>{{ product.grade }}</td>
                    {% endif %}
                </tr>
            {% endfor %}
                <tr><a href="{% url 'rank:show_product' %}">详情</a></tr>
        </tbody>
    </table>
        <h4>二号食堂</h4>
        <a href="{% url 'rank:show_product' %}">详情</a>
         <table class="cart">
            <tbody>
                <tr>
                    <th>菜名</th>
                    <th>价格</th>
                    <th>余量</th>
                    <th>人气值</th>
                </tr>
                {% for product in product2 %}
                    <tr>
                        {% if product.restaurant.name == '二号食堂' %}
                            <td><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></td>
                            <td>￥{{ product.price }}</td>
                            <td>{{ product.stock }}</td>
                            <td>{{ product.grade }}</td>
  
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <h4>三号食堂</h4>
         <table class="cart">
            <tbody>
                <tr>
                    <th>菜名</th>
                    <th>价格</th>
                    <th>余量</th>
                    <th>人气值</th>
                </tr>
                {% for product in product3 %}
                    <tr>
                        {% if product.restaurant.name == '三号食堂' %}
                            <td><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></td>
                            <td>￥{{ product.price }}</td>
                            <td>{{ product.stock }}</td>
                            <td>{{ product.grade }}</td>
  
                        {% endif %}
                    </tr>
                {% endfor %}
                    <tr><a href="{% url 'rank:show_product' %}">详情</a></tr>
            </tbody>
        </table>
        <h4>四号食堂</h4>
         <table class="cart">
            <tbody>
                <tr>
                    <th>菜名</th>
                    <th>价格</th>
                    <th>余量</th>
                    <th>人气值</th>
                </tr>
                {% for product in product4 %}
                    <tr>
                        {% if product.restaurant.name == '四号食堂' %}
                            <td><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></td>
                            <td>￥{{ product.price }}</td>
                            <td>{{ product.stock }}</td>
                            <td>{{ product.grade }}</td>
  
                        {% endif %}
                    </tr>
                {% endfor %}
                    <tr><a href="{% url 'rank:show_product' %}">详情</a></tr>
            </tbody>
        </table>
        <h4>五号食堂</h4>
         <table class="cart">
            <tbody>
                <tr>
                    <th>菜名</th>
                    <th>价格</th>
                    <th>余量</th>
                    <th>人气值</th>
                </tr>
                {% for product in product5 %}
                    <tr>
                        {% if product.restaurant.name == '五号食堂' %}
                            <td><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></td>
                            <td>￥{{ product.price }}</td>
                            <td>{{ product.stock }}</td>
                            <td>{{ product.grade }}</td>
  
                        {% endif %}
                    </tr>
                {% endfor %}
                    <tr><a href="{% url 'rank:show_product' %}">详情</a></tr>
            </tbody>
        </table>
        <h4>人气榜</h4>
        <table class="cart">
            <tbody>
                <tr>
                    <th>菜名</th>
                    <th>价格</th>
                    <th>人气值</th>
                </tr>
                {% for product in products_rank %}
                    <tr>
                        <td><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></td>
                        <td>￥{{ product.price }}</td>
                        <td>{{ product.grade }}</td>
                    </tr>
                {% endfor %}
                    <tr><a href="{% url 'rank:show_product' %}">详情</a></tr>
            </tbody>
        </table>
        
   
        
    </div>  
{% endblock %}  
    
  

rank/templates/rank/product/list3.html
{% extends "rank/base.html" %}
{% load static %}

{% block title %}
    登录
{% endblock %}

{% block content %}
    <div>
        <h1>登录<h1>
    </div>
<form action="product.list2.html" method="get">
    {{ form.as_p }}
    <p><input type="submit" value="登录"></p>
    {% csrf_token %}
</form>
{% endblock %}  
    
  

rank/templates/rank/product/search.html
{% extends "rank/base.html" %}
{% load static %}

{% block title %}
    搜索结果
{% endblock %}

{% block content %}
    <div>
        <table class="cart">
            <thead>
                <h2>您是不是想找</h2>
            </thead>
            <tbody>
                <tr>
                    <th>菜名</th>
                    <th>食堂</th>
                    <th>价格<th>
                    <th>余量</th>
                </tr>
                {% for c in post_list %}
                    <tr>
                        <td><a href="{{ c.get_absolute_url }}">{{ c.name }}</a><td>
                        <td>{{ c.restaurant.name }}</td>
                        <td>{{ c.price }}</td>
                        <td>{{ c.stock }}<td>
                        <td><a href="{% url "rank:product_detail" id=c.id slug=c.slug %}">去看看</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

rank/templates/rank/product/show_me.html
{% extends "rank/base.html" %}
{% load static %}

{% block title %}
    个人中心
{% endblock %}

{% block content %}
    <div id="me">
        {% for c in myself %}
            <h1>
                {{c.name}}
            </h1>
            <h2>
            我的余额：
            {{ c.balance }}
            </h2>
        {% endfor %}
       
            <table class="cart">
                <thread>待评价订单</thread>
                <tbody>
                    <tr>
                        <th>订单详情</th>
                        <th>订单编号</th>
                        <th>数量</th>
                        <th>价格</th>
                    </tr>
                    {% for a in order %}
                        {% for b in orderitems %}
                            <tr>    
                                {% if b.order == a %}
                                    <td><a href="{{ b.product.get_absolute_url }}">{{ b.product.name }}</a></td>
                                    <td>{{ b.order.id }}</td>
                                    <td>{{ b.quantity }}</td>
                                    <td>{{ b.price }}</td>
                                    <td><a href="{% url "rank:comment_create" product_slug=b.product.slug order_id=b.order.id%}">去评价</a></td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    {% endfor %}
                </tbody>
            </table>
    </div>
    <div id="me">
        <table class="cart">
            <thead>
                已评价订单
            </thead>
            <tbody>
                <tr>
                    <th>订单详情</th>
                    <th>订单编号</th>
                    <th>数量</th>
                    <th>价格</th>
                </tr>
                {% for a in order2 %}
                    {% for b in orderitems %}
                        {% if b.order == a %}
                            <tr>
                                <td><a href="{{ b.product.get_absolute_url }}">{{ b.product.name }}</a></td>
                                <td>{{ b.order.id }}</td>
                                <td>{{ b.quantity }}</td>
                                <td>{{ b.price }}</td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

rank/templates/rank/product/show_product.html
{% extends "rank/base.html" %}
{% load static %}

{% block title %}
    {% if restaurant %}{{ restaurant.name }}{% else %}菜品{% endif %}
{% endblock %}

{% block content %}
    <div id="sidebar">
        <h3>类别</h3>
        <ul>
            <li {% if not restaurant %}class="selected"{% endif %}>
                <a href="{% url "rank:show_product" %}">全部</a>
            </li>
        {% for c in restaurants %}
            <li {% if restaurant.slug == c.slug %}class="selected"{% endif %}>
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
        {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if restaurant %}{{ restaurant.name }}{% else %}菜品{% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img class="my-img" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"></br>
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                ￥{{ product.price }}
            </div>
        {% endfor %}
    </div>
{% endblock %} 